### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by joshua-gatto**
Logs and stores  all CRUD methods with meaningful data in a file.

### CODE REVIEW

**Comment by GillesMyny1** [comment]
Nice work! Why are you using the @After and @Around annotation? Why not just @Around?

**Comment by joshua-gatto** [comment]
> Nice work! Why are you using the @after and @around annotation? Why not just @around?

I used the @After annotation since the object's IDs are only set after the row is inserted into the table and I wanted to be able to log the objects along side their primary key.  
  
I only used the @Around annotation in one instance because I needed to maintain context on both sides of a method's execution. In this case, I used it to time the execution of the methods. To do this with the other advice would create unnecessary overhead with the .proceed() method.

**Comment by dowy24** [comment]
There seems to be a test failing for some reason, I will see if I can find a fix.

**Comment by joshua-gatto** [comment]
> There seems to be a test failing for some reason, I will see if I can find a fix.

The test only seems to fail on 

> There seems to be a test failing for some reason, I will see if I can find a fix.

I ran the tests locally and they are still failing. It seems that the survey on line 42 in the addSurveyTest() is null. I will be looking into this today.

**Comment by joshua-gatto** [comment]
> > There seems to be a test failing for some reason, I will see if I can find a fix.
> 
> 
> 
> The test only seems to fail on 
> 
> 
> 
> > There seems to be a test failing for some reason, I will see if I can find a fix.
> 
> 
> 
> I ran the tests locally and they are still failing. It seems that the survey on line 42 in the addSurveyTest() is null. I will be looking into this today.

Fixed the issue of addSurveyTest() failing due to null survey response.

**Pull request merged**
