### PR TITLE
Add Text QnA results view

### PR DESCRIPTION
**Pull request by Razem999**

### CODE REVIEW

**Comment by GillesMyny1** [comment]
One small question, is it more difficult, implementation wise, to display it in this fashion compared to a basic table format?

Otherwise, looks great!

**Comment by Razem999** [comment]
> One small question, is it more difficult, implementation wise, to display it in this fashion compared to a basic table format?
> 
> Otherwise, looks great!

It is probably easier to do it in a table format, though for user interface purposes, it is easier to read the questions and answers listed in this fashion. Following the columns and rows in a table, one question could have many answers, and many answers under one question could lead to huge blank spaces under the question itself.

**Comment by dowy24** [comment]
Are we just passing textQnA attribute to account for the textAnswers too? Won't it be better to have a separate attribute for textAnswers?

**Comment by Razem999** [comment]
> Are we just passing textQnA attribute to account for the textAnswers too? Won't it be better to have a separate attribute for textAnswers?

Since the answers to the questions are already under the textQnA object, I thought might as well grab the answers associated with each of the textQnA object. And this required just one line of code in the SurveyWebController for it to be accessible in the html files.

**Pull request merged**
